### PR TITLE
add pt-br lang support

### PR DESCRIPTION
**Pull request by lucassmacedo**

### CODE REVIEW

**Comment by jersobh** [comment]
Come on, pull this one pls :+1:

**Comment by jersobh** [comment]
:(

**Comment by lucassmacedo** [comment]
I will.

**Comment by MoraesGil** [comment]
thanks for add pt-br but you forgot of update in npm =) 2018

**Comment by MoraesGil** [comment]
Is it availiable?

**Comment by lvkai0807** [comment]
怎么联系你啊 。  在整合你这个日历的时候路径不对

**Pull request closed without merging**
